/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <UART.h>
#include <UART_SPI_UART.h>
#include <UART_PINS.h>
#include <UART_SPI_UART_PVT.h>
#include <UART_PVT.h>
#include <TX_LED.h>
#include <TX_LED_aliases.h>
#include <RX_LED.h>
#include <RX_LED_aliases.h>
#include <UART_RX_ISR.h>
#include <I2C_MPU6050.h>
#include <I2C_MPU6050_I2C.h>
#include <I2C_MPU6050_PINS.h>
#include <I2C_MPU6050_I2C_PVT.h>
#include <I2C_MPU6050_PVT.h>
#include <UART_tx.h>
#include <UART_tx_aliases.h>
#include <UART_rx.h>
#include <UART_rx_aliases.h>
#include <I2C_MPU6050_sda.h>
#include <I2C_MPU6050_sda_aliases.h>
#include <I2C_MPU6050_scl.h>
#include <I2C_MPU6050_scl_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

